### ISSUE TITLE
Jackal Seems Broken, Release Source?

### ISSUE THREAD

**Issue by spencerthayer** [tpkahlon/javascript#4]
Hi, it seems like Jackal is broken. Is there any chance you'll release the source code so that people can get this working again? Thanks!

**Comment by tpkahlon** [comment]
Hello @spencerthayer,

Source code for `Jackal` application is available in folder `m3u8player`.

I am using an unlimited fork of [CORS-anywhere](https://cors-anywhere.herokuapp.com/) project. However, network calls get exhausted after a certain limit. That is why application is not able to make network calls after a certain interval because of CORS error.
